# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

#osx_image: xcode12
#language: swift
# objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/XYNav.xcworkspace -scheme XYNav-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint

osx_image: xcode12
language: swift5.0
cache: cocoapods
xcode_project: XYNav/Example/XYNav.xcworkspace
xcode_scheme: XYNav-Example
podfile: XYNav/Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
#- pod install --project-directory=Example
- cd XYNav/Example
- pod update
script:
- cd ../
- pod lib lint
